### ISSUE TITLE
Auto-Detect wiki

### ISSUE THREAD

**Issue by jkroll20** [wmde/DeepCat-Gadget#19]
In the prototype, the request url (var requestUrl) is hardcoded to reference our test instance. This has to be adjusted for every wiki it is rolled out to. Even better would be some kind of auto-detection. E.g.: If the Gadget was requested from de.wikipedia.org, get .../catgraph-jsonp/dewiki_ns14/... and same thing for other wikis/languages.

**Comment by WMDE-Fisch** [comment]
See pull request. This does not work for the gptest1 wiki. The wgContentLanguage there is "de".

The change is already live in:

User:Christoph_Fischer_(WMDE)/Gadgets/DeepCat.js on de.WP.org and en.WP.org
