### ISSUE TITLE
String.format

### ISSUE THREAD

**Issue by jkroll20** [wmde/DeepCat-Gadget#25]
[String.format](https://github.com/wmde/DeepCat-Gadget/commit/b6b7a9470861e664ec6e575407a19f7bbe7a79fd) is polluting the namespace with this nonstandard function, right? I'm not very familiar with modern JS, but does this apply even to scripts loaded after this one? In either case, I don't like it. If there's no very good reason to do it like this, I suggest you make it a normal function which takes a String as an argument, local to our main fn.

**Comment by thiemowmde** [comment]
Yes, this code will
* overwrite a possibly existing String.format function and
* still be available to other code.

Adding methods to prototypes is fine in environments you control. But gadgets should not do this.

**Comment by jkroll20** [comment]
thx
