### ISSUE TITLE
Decide on coding convention

### ISSUE THREAD

**Issue by wmde-manicki** [wmde/DeepCat-Gadget#50]
As more people started contributing to gadget's code, some slight differences in coding conventions used by different people (myself included) started to appear.

For instance, we are most often not putting a whitespace after the `function` keyword, e.g.
```js
DeepCat.ResponseErrors.reset = function() {
```
There are several exceptions in gadgets code, though:
```js
$( '#searchText' ).find( ':input' ).on( 'keyup', function () {
```
On the other hand, the latter style is currently broadly used in unit tests.

These are really small differences but I think it would reasonable to decide on one of these and stick to this particular convention in future.

Apparently, the convention used in the first example above seems to be following MediaWiki convention: https://www.mediawiki.org/wiki/Manual:Coding_conventions/JavaScript#Whitespace, while the other example is an example of Wikibase convention: https://www.mediawiki.org/wiki/Wikibase/Coding_conventions#JavaScript_style_policies.
These conventions are surely good examples to follow, we don't need to come up with our own convention (and should not do so).

@thiemowmde has somehow implicitly suggested using Wikibase style in https://github.com/wmde/DeepCat-Gadget/pull/22.
I don't have any preference, both are fine.
@WMDE-Fisch you have written most of gadget's code, what's your opinion?
Others, please also comment on this.

Once the decision has been made, I can voluntarily adapt current code of gadget and unit tests to the chosen style.

**Comment by WMDE-Fisch** [comment]
Hmmm yeah the whitspace. Most of the code I contributed at the beginning had it due to the fact that my PHPStorm puts it there when running auto-format. 

I haven't found a way to prevent PHPStrom putting it there. So until someone can show me how to fix that I personally would prefer having it so I can use auto-format again ;-).

**Comment by jakobw** [comment]
@WMDE-Fisch Settings > Editor > Code Style > JavaScript > Spaces > Uncheck "In function expression"

**Comment by WMDE-Fisch** [comment]
damn :-) - okay ... then ... Wikibase convention?

**Comment by wmde-manicki** [comment]
Okay, so I have just posted a pull request: https://github.com/wmde/DeepCat-Gadget/pull/51.

There is `.jscsrc` file include, so the code could be checked against the style policy from command line, or even from PhpStorm.
